config/routes.rb
Rails.application.routes.draw do
  root 'tests#jq_grid'

  scope '/city' do
    get '/list(.:format)', to: 'cities#index', as: 'cities_index'
    get '/sample(.:format)', to: 'cities#sample', as: 'cities_sample'
    get '/jq-batch', to: 'cities#jq_batch', as: 'cities_jq_batch'
    get '/ng-batch', to: 'cities#ng_batch', as: 'cities_ng_batch'
  end

  scope '/test' do
    get '/jq-grid', to: 'tests#jq_grid', as: 'tests_jq_grid'
    get '/ng-grid', to: 'tests#ng_grid', as: 'tests_ng_grid'
    get '/jq-widgets', to: 'tests#jq_widgets', as: 'tests_jq_widgets'
    get '/kendo', to: 'tests#kendo_grid', as: 'tests_kendo_grid'
    get '/holdings-print', to: 'fakes#holdings_print', as: 'fakes_holdings_print'
    get '/holdings-print-schema', to: 'fakes#holdings_print_schema', as: 'fakes_holdings_print_schema'
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  class << self
    def random
      limit(1).offset(rand(count)).first
    end
  end

  def in_json
    {
        id: self.id,
        name: self.name,
        zip: self.zip,
        time_zone: self.time_zone,
        state: self.state,
        country: self.country
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def sample
    @city = City.random

    respond_to do |format|
      format.json {render json: @city.in_json}
    end
  end

  def index
    @cities = City.all

    respond_to do |format|
      format.json {render json: @cities.map(&:in_json)}
    end
  end

  def jq_batch
    page = params[:page].to_i
    limit = params[:rows].to_i
    sidx = params[:sidx]
    sord = params[:sord]

    sidx = 1 if sidx.nil?
    limit = params[:totalrows].to_i unless params[:totalrows].nil?

    count = City.count
    total_pages = if count > 0
      (count.to_f / limit.to_f).ceil
    else
      0
    end

    page = total_pages if page > total_pages
    limit = 0 if limit < 0
    start = limit * page - limit
    start = 0 if start < 0

    # code here
    cities = City.order('?', sidx).limit(limit).offset(start).map {|c| {id: c.id, cell: [c.id, c.name, c.zip, c.state, c.country, c.time_zone]}}

    response = {
        page: page,
        total: total_pages,
        records: count,
        rows: cities
    }

    respond_to do |format|
      format.json {render json: response}
    end
  end

  def ng_batch
    respond_to do |format|
      format.json {render json: City.all.map {|c| {id: c.id, name: c.name, zip: c.zip, state: c.state, country: c.country, time_zone: c.time_zone}}}
    end
  end
end

app/controllers/fakes_controller.rb
class FakesController < ApplicationController

  def holdings_print
    respond_to do |format|
      format.json {render json: 20000.times.map {|i| get_position("-#{i+1}")}}
    end
  end

  def holdings_print_schema
    respond_to do |format|
      format.json {render json: {data: 20000.times.map {|i| get_position("-#{i+1}")}}}
    end
  end

  private

  def get_position(postfix = '')
    {
        acctName: 'James, TA Trust Capital Access' + postfix,
        acctNum: '50450043',
        amountInv: nil,
        avgCostShare: nil,
        avgInvShare: nil,
        costBasis: nil,
        costBasisGL: nil,
        costBasisGLPerc: nil,
        current: 29426243.59,
        cusip: nil,
        daily: nil,
        dailyPerc: nil,
        desc: '2514 DIVERSIFIED L.P.',
        disp: '',
        estAnnInc: nil,
        estAnnYield: nil,
        hasOpen: false,
        hasTaxlots: false,
        id: '50450043_Cash',
        amountInvGL: nil,
        amountInvGLPerc: nil,
        isMarginTypeLoc: false,
        isTrust: false,
        mAgreements: false,
        percPort: 0.0398826162095903,
        plans: nil,
        pType: nil,
        sourceAcct: nil,
        price: nil,
        priceChg: nil,
        priceChgPerc: nil,
        priceDate: nil,
        prdType: 0,
        detailedPrdType: 0,
        quan: nil,
        rschRating: nil,
        shortName: 'JAMES,TA CAP AC',
        suitability: 0,
        symCusip: 'CASH',
        typeLocs: nil,
        isSweepOption: true,
        underlying: nil,
        isMoney: true,
        dSym: 'CASH',
        coupon: nil,
        debt: ' ',
        factor: nil,
        fCallDate: nil,
        fCallPrice: nil,
        hasPrerefund: false,
        maturity: nil,
        modDuration: nil,
        nextPayAmount: nil,
        nextPayDate: nil,
        par: nil,
        ratings: nil,
        remainPrincVal: nil,
        sCallDate: nil,
        sCallPrice: nil,
        cashBalances: [
            {
                sortOrder: 3,
                description: 'EAGLE CLASS - JPMORGAN TAX FREE MONEY MARKET FUND*',
                amount: 29426243.59,
                estAnnInc: 2942.62,
                estAnnYield: 0.009999985186692326
          }
        ],
        yestValue: nil,
        isMCB: false,
        isMAI: false,
        isCash: false,
        currency: ' ',
        exRate: nil,
        nonUsPrice: nil,
        nonUsValue: nil,
        cultureCode: nil,
        advisor: '0002',
        status: 0,
        ar: 'tsg',
        ac: 'tst',
        stc: nil,
        mm5: nil,
        pc: nil,
        pi: 'cash',
        psc: 'brk',
        marginable: false,
        policy: nil,
        grpSrt: nil,
        multiTradable: false,
        tradeMenuType: 7,
        selected: false
    }
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def jq_grid
  end

  def ng_grid
  end

  def jq_widgets
  end

  def kendo_grid
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/fakes_helper.rb
module FakesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GdSeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://www.trirand.com/blog/jqgrid/themes/ui.jqgrid.css"/>
  <link rel="stylesheet" href="http://trirand.com/blog/jqgrid/themes/redmond/jquery-ui-custom.css"/>
  <link rel="stylesheet" href="http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css"/>
  <link rel="stylesheet" href="http://www.jqwidgets.com/jquery-widgets-documentation/jqwidgets/styles/jqx.base.css"/>
  <link rel="stylesheet" href="http://cdn.kendostatic.com/2014.3.1316/styles/kendo.common-material.min.css"/>
  <link rel="stylesheet" href="http://cdn.kendostatic.com/2014.3.1316/styles/kendo.material.min.css"/>
  <%= javascript_include_tag 'application.js' %>
</head>
<body>

<%= render partial: 'shared/top_menu' %>
<%= yield %>

</body>
</html>

app/views/shared/_top_menu.html.erb
<div class="b-menu">
  <div class="b-container ui secondary pointing menu">
    <%= link_to 'jqGrid', tests_jq_grid_path, class: current_page?(tests_jq_grid_path) ? 'active item' : 'item' %>
    <%= link_to 'ngGrid', tests_ng_grid_path, class: current_page?(tests_ng_grid_path) ? 'active item' : 'item' %>
    <%= link_to 'jqWidget', tests_jq_widgets_path, class: current_page?(tests_jq_widgets_path) ? 'active item' : 'item' %>
    <%= link_to 'kendo', tests_kendo_grid_path, class: current_page?(tests_kendo_grid_path) ? 'active item' : 'item' %>
  </div>
</div>